### ISSUE TITLE
how to make it easy to  run ./run.sh twice?

### ISSUE THREAD

**Issue by scil** [jtstorck/containerized-ambari#7]
this project is wonderful!

When the second I run `./run.sh` and failed 
```
vagrant@1:/vagrant/www/vendors/containerized-ambari/docker/scripts$ ./run.sh -d -c -n 2
ambari-bridge network already exists, not creating
Starting database container
docker: Error response from daemon: Conflict. The container name "/postgres" is already in use by container "0da5ec7a5b0f3993621981720aab18a1c5bd31ec3a372b5438b2cc71b9a33139". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
Starting traefik container
docker: Error response from daemon: Conflict. The container name "/traefik" is already in use by container "a881270301005d47aec024efbf7ffeb441ab82fe37257356a22aa412051bf360". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
Starting ambari-server container
docker: Error response from daemon: Conflict. The container name "/ambari-server" is already in use by container "1bfcbf7f49c794e059b8906b780af6d4208bc3c3d17bc4c6aaa18179f30cc7f1". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
Starting 2 ambari-agent containers
docker: Error response from daemon: Conflict. The container name "/ambari-node-1" is already in use by container "4b662e6c1dce7fff52111300ba86fd6f65a4572dc809e270e2a163d34e54f1ea". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
docker: Error response from daemon: Conflict. The container name "/ambari-node-2" is already in use by container "aebace2a9dec75489f01c5e2a54ed73cd2683e43bd5c02ba7022862994b5ecf5". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

```

would it possible to run there containers mulitple times?

And, after I ` docker rm` all containers, I run ` ./run.sh -d -c -n 2` and ` curl http://172.18.0.4:8080' , I got
 ```
curl: (7) Failed to connect to 172.18.0.4 port 8080: Connection refused
```

172.18.0.4:8080 is what I found in http://localost:8080/dashboard/ and was available the first time.

logs:

```
> docker logs -f ambari-server
Using python  /usr/bin/python
Starting ambari-server
Ambari Server running with administrator privileges.
Organizing resource files at /var/lib/ambari-server/resources...
Ambari database consistency check started...
Server PID at: /var/run/ambari-server/ambari-server.pid
Server out at: /var/log/ambari-server/ambari-server.out
Server log at: /var/log/ambari-server/ambari-server.log
Waiting for server start...........................ERROR: Exiting with exit code -1.
REASON: Ambari Server java process has stopped. Please check the logs for more information.
        at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98)
        ... 14 more
```

and 

```
> docker logs -f postgres
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start


WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
****************************************************
WARNING: No password has been set for the database.
         This will allow anyone with access to the
         Postgres port to access your database. In
         Docker's default configuration, this is
         effectively any other container on the same
         system.

         Use "-e POSTGRES_PASSWORD=password" to set
         it in "docker run".
****************************************************
waiting for server to start....LOG:  database system was shut down at 2018-10-27 11:47:18 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
 done
server started
ALTER ROLE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
waiting for server to shut down....LOG:  shutting down
LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

LOG:  database system was shut down at 2018-10-27 11:47:21 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
FATAL:  role "ambari" does not exist
FATAL:  role "ambari" does not exist
FATAL:  role "ambari" does not exist
FATAL:  role "ambari" does not exist
```

**Comment by jtstorck** [comment]
If you want to scale the number of Ambari nodes up or down, it should probably be done via docker-compose.  There's another issue (#5) and PR (#6) for integrating docker-compose into the project. It would probably take some rework of the scripts to get it to work properly, though.
